name: encrypt
version: 2.0.0
description: A set of high-level APIs over PointyCastle for two-way cryptography.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/encrypt

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  asn1lib: ^0.5.3
  collection: ^1.14.11
  pointycastle: ^1.0.0

dev_dependencies:
  test: ^1.5.1+1
