name: encrypt
version: 5.0.4
description: A set of high-level APIs over PointyCastle for two-way cryptography.
repository: https://github.com/leocavalcante/encrypt

executables:
  secure-random:

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.3.1
  asn1lib: ^1.5.0
  clock: ^1.1.1
  collection: ^1.17.0
  crypto: ^3.0.2
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0

false_secrets:
 - /test/*.pem
